language: python
python:
#  - "2.7"
# - "3.5"
  - "3.6"
# command to install dependencies
cache: pip
install:
  - pip install cython
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install .
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py install  
# command to run tests
script:
    - cd tests
    - nosetests --with-coverage --cover-package=pysd
    - coveralls
